config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  # sessioncontroller
  get 'login', to: 'sessions#new' 
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :edit, :show]
  
  resources :tasks, only: [:create, :destroy, :new, :edit, :show, :update, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user # UserとTasksの一対多を表現
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
# バリデーション
class User < ApplicationRecord
  # テーブルに保存される全てのメアドは小文字に変換される
  before_save { self.email.downcase! } 
  validates :name, presence: true, length: { maximum: 50 } # nameのvalidation カラを許さず50文字以内
  validates :email, presence: true, length: { maximum: 255 }, # emailのvalidation " 255文字以内
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, # メアドの正しい形式
                    uniqueness: { case_sensitive: false } # 重複を許さないバリデーション(大文字&小文字を区別しない)
  has_secure_password
  
  has_many :tasks # 一対多を表現
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper # => ControllerからHelperのメソッドを使えるようにする処理
  
  private # ログイン要求処理

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_tasks = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
# ログイン関係を担当
class SessionsController < ApplicationController
  def new
  end
# params にフォームデータは代入されている
  def create 
    # 取り出す時の二段階指定して取得
    email = params[:session][:email].downcase #フォームデータの email を小文字化して取得
    password = params[:session][:password] 
    if login(email, password) # ログイン可能なメソッドが定義、ログインに成功すればtrueを返し、失敗すればfalseを返す仕様
      flash[:success] = 'ログインに成功しました。'
      # 成功時、@userのusers#showへとリダイレクト
      redirect_to @user 
    else
      # 失敗時、render 'new'によりsessions/new.html.erbを再表示する
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy # ログアウト機能
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url # ログアウト後は、TOPにリダイレクトさせる。
  end
  
  # login(email, passsword) をprivateで定義
  private
  
  def login(email, password)
    @user = User.find_by(email: email) # 入力フォームのemailと同じメアドを持つユーザを検索し@userへ代入
    #  if @userで @userが存在するかを確認している。
    if @user && @user.authenticate(password) # @userのパスワードが合っているか、email,passwordの組み合わせが間違っていた場合には、ログインできない仕様
      # ログイン成功
      session[:user_id] = @user.id # ブラウザにはCookieとして、サーバにはSessionとして、ログイン状態が維持
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    # ログインしているユーザーの、全タスクを取得する
    @tasks = current_user.tasks.all
  end
  
  def show
  end
  
  def new
    @task = current_user.tasks.new
  end
  
  def create
    @task = current_user.tasks.build(task_params)
    # binding.pry # こう書くと、ここで、処理が一度止まります
    if @task.save
      flash[:success] = 'Taskが正常に投稿されました。'
      redirect_to root_url
    else
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page])
      flash.now[:danger] = 'Taskの投稿に失敗しました。'
      render 'toppages/index'
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = 'Taskは正常に削除されました'
    redirect_back(fallback_location: root_path)
  end
  
  def edit
    # モデル名は「1文字目が大文字」かつ「単数形」で表記します
    # なので Task になります
    # models/task.rb の「クラス名」と一致しています
    # @task = Task.find(params[:id])
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'task は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'task は更新されませんでした'
      render :edit
    end
  end
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  # Strong Parameter
  def task_params
    params.require(:task).permit(:content, :status, :user_idm)
  end
  
  def correct_user # 削除しようとしているMicropostが本当にログインユーザが所有しているものかを確認している。
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url #見つからなければトップページに戻されます。
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @user = current_user
      @task = current_user.tasks.build # form_for用 カラのインスタンスを代入
      @tasks = current_user.tasks.order('created_at DESC').page(params[:page]) #一覧表示用
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action　=> only:で指定されたアクションに対して、事前処理を設定できる
  #1 require_user_logged_in => ログイン状態を確認し、ログインしていれば何もせず、
  #2 ログインしていなければログインページへ強制的にリダイレクトさせる。=> 会員制サービスの開発に流用可能
  before_action :require_user_logged_in, only: [:index, :show]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.order('created_at DESC').page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 現在ログインしているユーザを取得するメソッド
  def current_user 
  #1 @current_user に既に現在のログインユーザが代入されていたら何もせず、
  #2 代入されていなかったら User.find(...) からログインユーザを取得し、@current_user に代入する処理を1行で書いたもの
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user # 8.5 sessions#create Helper参照
  end  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    # user.email.downcaseしたものを暗号化（ダイジェスト）にしたもの => gravatar_id
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<!--エラーメッセージ-->
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TaskList</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>　<!--仮定記述-->
          <li><%= link_to 'Users', users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'My profile', user_path(current_user) %></li> <!--仮定記述-->
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Tasklist</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    <%= form_for(task) do |f| %>
      <% if task.errors.any? %>
        <div id="error_explanation">
          <ul>
            <% task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :content, 'タスク' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :status, 'ステータス' %>
        <%= f.text_field :status, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>    
  </div>
</div>

app/views/tasks/_tasks.html.erb
<!--共通のView-->
<ul class="media-list">
  <% tasks.each do |task| %>
    <% user = task.user %>
    <li class="media">
      <div class="media-left">
        <img class="media-object img-rounded" src="<%= gravatar_url(user, options = { size: 50 }) %>" alt="">
      </div>
      <div class="media-body">
        <div>
          <%= link_to user.name, user_path(user) %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
          <div>
            <p><%= task.content %></p>
          </div>
        </div>
      </li>
          <!--削除ボタン-->
          <% if current_user == task.user %>
            <%= link_to "Edit", edit_task_path(task), class: 'btn btn-info btn-xs' %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<!--パーシャル-->
<h1>id: <%= @task.id %> のタスク編集ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id, task %> : <%= task.status %> &gt; <%= task.content %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<!--パーシャル-->
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id = <%= @task.id %> の詳細ページ</h1>

<P>ステータス: <%= @task.status %></P>
<p>タスク: <%= @task.content %></p>


<%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'このタスクを編集する', edit_task_path(@task) %>
<%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/toppages/index.html.erb
<!--ログイン後にトップページの表示を変更-->
<!--ログイン後のトップページには自分の投稿したTasksが表示される-->
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <%= form_for(@task) do |f| %>
      <% if @task.errors.any? %>
        <div id="error_explanation">
          </ul>
            <% @task.errors.full_messages.each do |task| %>
              <li><%= task %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <!--タスクフォーム-->
        <div class="form-group">
          <%= f.label :content, 'タスク' %>
          <%= f.text_field :content, class: 'form-control', rows: 5 %>
        </div>
      <!--ステータスフォーム-->
        <div class="form-group">
          <%= f.label :status, 'ステータス' %>
          <%= f.text_field :status, class: 'form-control', rows: 5 %>
        </div>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-xs-8">
      <%= render 'tasks/tasks', tasks: @tasks %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the Tasklist</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<!--フォロー／フォロワーの表示に users/_users.html.erb は使用する => パーシャル-->
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <!--エラーメッセージがあるので追記-->
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Tasks <span class="badge"><%= @count_microposts %></span><% end %></li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Followers</a></li>
    </ul>
    <%= render 'tasks/tasks', tasks: @tasks %>
  </div>
</div>